channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=23.0.1
- pip:
  - mlflow==3.5.1
  - cloudpickle==3.1.1
  - numpy==2.3.4
  - pandas==2.3.3
  - psutil==7.1.1
  - pyarrow==21.0.0
  - scikit-learn==1.7.2
  - scipy==1.15.3
name: mlflow-env
