prepare:
  split: 0.2
  seed: 42

train:
  max_evals: 10 # Number of Hyperopt experiments
  seed: 42 
  # This search_space block will be read by Hyperopt
  search_space:
    n_estimators:
      type: quniform
      min: 50
      max: 200
      q: 50
    max_depth:
      type: quniform
      min: 5
      max: 20
      q: 1
